FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir --upgrade "duckdb[s3]" pyarrow

# Copy tất cả python files
COPY *.py ./

CMD ["python", "query_s3_direct.py"]
